import type { Metadata } from 'next';
import './globals.css';
import Provider from './components/Provider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
	title: 'Controle de despesas',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="pt-br" className="h-full">
			<body className="h-full">
				<Provider>
					{children}
					<ToastContainer limit={3} />
				</Provider>
			</body>
		</html>
	);
}
